version: '2.1'

services:
  inkyshot:
    build:
      context: ./inkyshot
    privileged: true
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: '1'
    environment: 
      - ALTERNATE_FREQUENCY=30
      - FONT=FredokaOne
      - MODE=alternate
      - QOD_CATEGORY=love
      - ROTATE
      - TEST_CHARACTER=a
      - TZ=Africa/Johannesburg
      - UPDATE_HOUR=6
      - WAVESHARE=1
      - WEATHER_INVERT
      - WEATHER_LOCATION
      #- INKY_MESSAGE=
  wifi-connect:
    build:
      context: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
    environment: 
      - PORTAL_SSID=PINK BABY